coordinates:
  name: config-chain
  provider: npmjs
  type: npm
revisions:
  1.1.10:
    licensed:
      declared: MIT
  1.1.11:
    licensed:
      declared: MIT
  1.1.12:
    files:
      - license: MIT
        path: package/package.json
    licensed:
      declared: MIT
