coordinates:
  name: apiextensions-apiserver
  namespace: kubernetes
  provider: github
  type: git
revisions:
  6510fd4369db6875dc897eedbd493edf500d2811:
    licensed:
      declared: Apache-2.0
  bbca0d3a19e3908bf6b7175119b8e00366e9c5f2:
    licensed:
      declared: Apache-2.0
