coordinates:
  name: pureconfig-generic_2.13
  namespace: com.github.pureconfig
  provider: mavencentral
  type: maven
revisions:
  0.11.1:
    licensed:
      declared: MPL-2.0
  0.17.1:
    licensed:
      declared: MPL-2.0
