coordinates:
  name: Aliencube.AzureFunctions.Extensions.Configuration.AppSettings
  provider: nuget
  type: nuget
revisions:
  1.0.1:
    licensed:
      declared: MIT
  1.1.0:
    licensed:
      declared: MIT
  1.2.0:
    licensed:
      declared: MIT
