coordinates:
  name: Aliencube.AzureFunctions.Extensions.OpenApi
  provider: nuget
  type: nuget
revisions:
  1.4.2:
    licensed:
      declared: MIT
  1.5.4:
    licensed:
      declared: MIT
  3.1.1:
    licensed:
      declared: MIT
