coordinates:
  name: ApplicationInsights.OwinExtensions
  provider: nuget
  type: nuget
revisions:
  0.2.0:
    licensed:
      declared: MIT
  0.3.0:
    licensed:
      declared: MIT
  0.4.0:
    licensed:
      declared: MIT
  0.4.1:
    licensed:
      declared: MIT
  0.5.0:
    licensed:
      declared: MIT
  0.5.1:
    licensed:
      declared: MIT
  0.6.0:
    licensed:
      declared: MIT
  0.8.1:
    licensed:
      declared: MIT
  0.9.0:
    licensed:
      declared: MIT
