coordinates:
  name: Microsoft.Extensions.Configuration
  provider: nuget
  type: nuget
revisions:
  2.0.0:
    licensed:
      declared: Apache-2.0
  2.0.1:
    licensed:
      declared: Apache-2.0
  2.1.0:
    licensed:
      declared: Apache-2.0
  2.1.0-preview1-final:
    licensed:
      declared: Apache-2.0
  2.1.0-preview2-final:
    licensed:
      declared: Apache-2.0
  2.1.1:
    licensed:
      declared: Apache-2.0
  2.2.0:
    licensed:
      declared: Apache-2.0
  5.0.0:
    described:
      sourceLocation:
        name: runtime
        namespace: dotnet
        provider: github
        revision: cf258a14b70ad9069470a108f13765e0e5988f51
        type: git
        url: 'https://github.com/dotnet/runtime/commit/cf258a14b70ad9069470a108f13765e0e5988f51'
