coordinates:
  name: Microsoft.ApplicationInsights.SnapshotCollector
  provider: nuget
  type: nuget
revisions:
  1.0.10:
    licensed:
      declared: OTHER
  1.4.3:
    licensed:
      declared: OTHER
