coordinates:
  name: go-swagger
  namespace: go-swagger
  provider: github
  type: git
revisions:
  8dfd9cdaac6292e37023827f9618397f495d62f3:
    licensed:
      declared: Apache-2.0
  b015bda48dfc648fdd95e7bc81dbb5cefc17c975:
    licensed:
      declared: Apache-2.0
