coordinates:
  name: ssh_config
  namespace: github.com%2Fkevinburke
  provider: golang
  type: go
revisions:
  v0.0.0-20180830205328-81db2a75821e:
    licensed:
      declared: MIT
  v0.0.0-20190724205821-6cfae18c12b8:
    licensed:
      declared: MIT
  v0.0.0-20190725054713-01f96b0aa0cd:
    licensed:
      declared: MIT
  v0.0.0-20201106050909-4977a11b4351:
    licensed:
      declared: MIT
