name: "Check for conflicts"
on:
  push:
  pull_request_target:
    types: [synchronize]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: check if PRs have conflicts
        uses: eps1lon/actions-label-merge-conflict@v3
        with:
          dirtyLabel: "merge conflict"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          commentOnClean: |
            @${{github.actor}}
            Conflicts have been resolved. :thumbsup:
