name: "Check for conflicts"
on:
  pull_request_target:
      branches:
        - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: check if PRs have conflicts
        uses: eps1lon/actions-label-merge-conflict@releases/2.x
        with:
          dirtyLabel: "merge conflict"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          commentOnClean: |
            @${{github.actor}}
            Conflicts have been resolved, release can now continue.
