name: "Check for conflicts"
on:
  # So that PRs touching the same files as the push are updated
  push:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: check if PRs have conflicts
        uses: eps1lon/actions-label-merge-conflict@releases/2.x
        with:
          dirtyLabel: "merge conflict"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          commentOnClean: "@${github.actor} Conflicts have been resolved."
